"""Add system settings table

Revision ID: 5065e01ca9ab
Revises: 1f05777320b2
Create Date: 2026-04-21 12:04:39.837300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5065e01ca9ab'
down_revision: Union[str, None] = '1f05777320b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))
        batch_op.drop_index(batch_op.f('ix_system_settings_id'))

    op.drop_table('system_settings')
    # ### end Alembic commands ###
